/*
  # Import Case Studies Part 2

  Import second batch of case studies
*/

INSERT INTO case_studies (id, title, industry, category, challenge, solution, result, duration, company, detailed_description, technologies, outcomes, tags, image_url, date, is_active, created_at, updated_at)
VALUES 
  ('2a7f702a-87b0-4b4d-922a-cfe00aebb6be', 'Telematik für Sonderbaumaschinen', 'Baumaschinen', 'Smart Mobility', 'Intelligente Vernetzung von Informationen für bessere Produktivität', 'All-in-One-Lösung mit 360-Grad-Flottenverwaltung und Echtzeit-Überwachung', 'Signifikante Senkung der Verwaltungsaufwände und gesteigerte Maschinenproduktivität', '12 Monate', 'Baumaschinenverleih', 'Moderne Telematik ist mehr als Fahrzeugortung – sie ist die intelligente Vernetzung von Informationen. Mit der flexiblen All-in-One-Lösung verbindet Batix die GPS-Verfolgung mit einer 360-Grad-Flottenverwaltung. Dazu gehören die Echtzeit-Ansicht des täglichen Maschinenbetriebs, die Erfassung relevanter Betriebsdaten und die sichere Übertragung der Daten.', '["GPS-Verfolgung","360-Grad-Flottenverwaltung","Echtzeit-Datenerfassung","Sichere Datenübertragung"]'::jsonb, '["Reduzierte Verwaltungsaufwände","Gesteigerte Produktivität","Verbesserte Maschinenauslastung","Transparente Einsatzhistorie"]'::jsonb, '["Telematik","Flottenverwaltung","IoT"]'::jsonb, NULL, '2020-08-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00'),
  ('2cb9a528-df03-4dc8-9c1e-4273adef9e56', 'Swiss Transit Lab - Open Doors', 'Öffentlicher Verkehr', 'Smart Mobility', 'Barrierefreier Zugang zur Mobilität für Menschen mit Beeinträchtigungen', 'Intelligente Vernetzung von Bussen mit Lift-Systemen über Haltewunschtaster', 'Nahtloser Umstieg ohne Zeitverlust für Rollstuhlfahrer', '6 Monate', 'Verkehrsbetriebe Schaffhausen', 'Mit dem Projekt ''Open Doors'' verknüpft das Swiss Transit Lab Teile der Mobilitätskette intelligent miteinander. Die Busse der Verkehrsbetriebe Schaffhausen werden dabei mit dem Lift im Regionalbuszentrum vernetzt. Bei Betätigung des Rollstuhl-Haltewunschtasters wird das Signal an eine Software von Batix übermittelt, die den Lift zeitverzögert auf die obere Ebene bestellt.', '["IoT-Vernetzung","Haltewunschtaster-System","Lift-Steuerung","Zeitgesteuerte Automation"]'::jsonb, '["Nahtloser Umstieg ohne Zeitverlust","Verbesserte Barrierefreiheit","Intelligente Mobilitätskette","Erhöhte Selbständigkeit"]'::jsonb, '["Barrierefreiheit","IoT","Vernetzung"]'::jsonb, NULL, '2021-11-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00')
ON CONFLICT (id) DO NOTHING;
