-- Insert some sample case studies for testing
INSERT INTO case_studies (
  title,
  industry,
  category,
  challenge,
  solution,
  result,
  duration,
  company,
  detailed_description,
  technologies,
  outcomes,
  tags,
  date,
  is_active
) VALUES 
(
  'Digitalisierung der Produktion',
  'Maschinenbau',
  'Smart Factory',
  'Ineffiziente manuelle Prozesse in der Fertigung führten zu hohen Kosten und langen Durchlaufzeiten.',
  'Implementierung eines MES-Systems mit IoT-Sensoren zur Echtzeitüberwachung der Produktion.',
  'Reduzierung der Durchlaufzeiten um 30% und Kosteneinsparungen von 15% pro Jahr.',
  '8 Monate',
  'TechCorp Manufacturing',
  'Das Projekt umfasste die komplette Digitalisierung der Produktionslinie mit Integration von IoT-Sensoren, MES-System und automatisierten Reporting-Tools.',
  '["IoT Sensoren", "MES System", "Azure Cloud", "Power BI"]',
  '["30% weniger Durchlaufzeit", "15% Kosteneinsparung", "100% Transparenz in der Produktion"]',
  '["Smart Factory", "IoT", "Digitalisierung", "MES"]',
  '2024-06-15',
  true
),
(
  'Intelligente Verkehrssteuerung',
  'Öffentlicher Verkehr',
  'Smart Mobility', 
  'Verkehrsstaus und ineffiziente Ampelschaltungen verursachten lange Wartezeiten im Stadtverkehr.',
  'KI-basierte Verkehrssteuerung mit adaptiven Ampelsystemen und Echtzeitdatenanalyse.',
  'Verbesserung des Verkehrsflusses um 25% und Reduzierung der CO2-Emissionen um 20%.',
  '12 Monate',
  'Stadt München',
  'Entwicklung und Implementierung eines intelligenten Verkehrsmanagementsystems mit KI-Algorithmen zur optimalen Ampelsteuerung basierend auf Echtzeit-Verkehrsdaten.',
  '["KI Algorithmen", "IoT Sensoren", "Cloud Computing", "Datenanalyse"]',
  '["25% besserer Verkehrsfluss", "20% weniger CO2-Emissionen", "Reduzierte Wartezeiten"]',
  '["Smart Mobility", "KI", "Verkehr", "IoT"]',
  '2024-04-20',
  true
),
(
  'Predictive Analytics für Wartung',
  'Energiewirtschaft',
  'Smart Data',
  'Ungeplante Anlagenausfälle verursachten hohe Kosten und Produktionsunterbrechungen.',
  'Machine Learning Modelle zur Vorhersage von Wartungsbedarfen basierend auf Sensordaten.',
  'Reduzierung ungeplanter Ausfälle um 40% und Optimierung der Wartungskosten um 25%.',
  '6 Monate',
  'Energie AG',
  'Entwicklung von Predictive Maintenance Lösungen mit Machine Learning zur frühzeitigen Erkennung von Wartungsbedarfen in Kraftwerksanlagen.',
  '["Machine Learning", "Python", "TensorFlow", "Azure ML", "Power BI"]',
  '["40% weniger ungeplante Ausfälle", "25% niedrigere Wartungskosten", "Verbesserte Anlagenverfügbarkeit"]',
  '["Smart Data", "Machine Learning", "Predictive Maintenance", "Energiewirtschaft"]',
  '2024-08-10',
  true
);