/*
  # Import Case Studies Part 4

  Import fourth batch of case studies
*/

INSERT INTO case_studies (id, title, industry, category, challenge, solution, result, duration, company, detailed_description, technologies, outcomes, tags, image_url, date, is_active, created_at, updated_at)
VALUES 
  ('7a6ab1e9-601f-42bf-8574-0d9a1daae114', 'ÖPNV Integrationslösung', 'Öffentlicher Verkehr', 'Smart Mobility', 'Abbildung aller Geschäftsprozesse in Verkehrsunternehmen', 'Webbasierte Anwendungen mit bidirektionalen Schnittstellen', 'Echtzeit-Datenverfügung für alle Unternehmensbereiche', '15 Monate', 'Regionale Verkehrsbetriebe', 'Die Integrationslösung für Verkehrsunternehmen verfügt über eine Vielzahl komplett webbasierter Anwendungen, die speziell auf die Bedürfnisse und Anforderungen von regionalen und überregionalen, privaten sowie kommunalen Verkehrsunternehmen zugeschnitten sind. Die Lösung enthält individuelle bidirektionale Schnittstellen und lässt sich problemlos in eine vorhandene IT-Landschaft integrieren.', '["Webbasierte Anwendungen","Bidirektionale Schnittstellen","IBIS-Bus Integration","Telematik-Systeme"]'::jsonb, '["Echtzeit-Datenverfügung","Ortsunabhängiger Zugriff","Nahtlose IT-Integration","Umfassende Prozessabbildung"]'::jsonb, '["ÖPNV","Integration","Echtzeit"]'::jsonb, NULL, '2019-05-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00'),
  ('ac302306-5740-4013-b05c-62d27add1a07', 'Qualitätsdatenanalyse QRS', 'Medizintechnik', 'Smart Data', 'Lückenlose Dokumentation und Datenintegration in der Röntgenröhrenproduktion', 'Digitales Qualitätsmanagementsystem mit direkter Datenerfassung', 'Zeitaufwand für Qualitätsprüfung von 10 Min auf 2 Sek reduziert', '8 Monate', 'Petrick GmbH', 'Interne Audits, Prüfungen, Sicherheitsrundgänge, Betriebsbegehungen und weitere Vor-Ort-Kontrollen sind ein wichtiger Bestandteil des betrieblichen Qualitätsmanagements. Diese Prüfungen & Checks können besonders effizient mit einem digitalen und transparenten Datenmanagement durchgeführt werden. Das System erzeugt für jede Röntgenröhre ein virtuelles Abbild – einen digitalen Zwilling.', '["Digitales Qualitätsmanagementsystem","Direkte Datenerfassung","Digitaler Zwilling","Automatisierte Prüfungen"]'::jsonb, '["Zeitreduktion von 10 Min auf 2 Sek","Lückenlose Dokumentation","Erhöhte Effizienz","Verbesserte Transparenz"]'::jsonb, '["Qualitätsmanagement","Datenintegration","Effizienz"]'::jsonb, NULL, '2018-10-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00')
ON CONFLICT (id) DO NOTHING;
