/*
  # Import Case Studies Part 3

  Import third batch of case studies
*/

INSERT INTO case_studies (id, title, industry, category, challenge, solution, result, duration, company, detailed_description, technologies, outcomes, tags, image_url, date, is_active, created_at, updated_at)
VALUES 
  ('649bf656-cb03-4563-a523-5aecf185e00e', 'Digitale Arbeitsplattform NOAH', 'Drehtechnik & Fertigung', 'Smart Factory', 'Vernetzung aller CNC-Maschinen und Mitarbeiter-Arbeitsplätze für optimale Maschinenauslastung', 'Entwicklung einer internen Arbeitsplattform mit KI-basierter Auftragssteuerung', '15% Senkung der Rüstkosten, 80% weniger Archivierungskosten, 90% weniger Suchkosten', '12 Monate', 'Drehtechnik Jakusch GmbH', 'Industrie 4.0 bestimmt maßgeblich die Zukunftsfähigkeit der Drehtechnik Jakusch GmbH. Seit 2016 setzt das Unternehmen auf digitale Technologien und hat damit ungeahnte Interaktions- und Gestaltungsräume gewonnen. Alle CNC-Maschinen und Mitarbeiter-Arbeitsplätze sind heute vernetzt und an die Datenerfassung angeschlossen. Alle Mitarbeiter nutzen die interne Arbeitsplatzform ''NOAH''. Der Einsatz von KI sorgt für eine optimale Maschinenauslastung und eine Auftragssteuerung. Die Produktion wird intelligent geplant, überwacht und dokumentiert – auch mit dem Mobiltelefon.', '["KI-basierte Auftragssteuerung","CNC-Maschinenvernetzung","Mobile Anwendungen","Datenerfassung"]'::jsonb, '["15% Senkung der Rüstkosten","80% Reduktion der Archivierungskosten","90% weniger Suchkosten","Optimale Maschinenauslastung"]'::jsonb, '["Industrie 4.0","KI","Prozessoptimierung"]'::jsonb, NULL, '2018-01-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-31T21:53:00.508257+00:00'),
  ('6c06b1c0-7119-4692-9b13-659f9b0ea3cf', 'Digitalstrategie MMS 4.0', 'Mittelstand', 'Smart Factory', 'Strategische Neuausrichtung traditioneller Geschäftsmodelle bis 2025', 'Experten-Tandem-Modell mit prozessgesteuertem Ansatz', 'Erfolgreiche digitale Transformation mit strukturierter Roadmap', '10 Monate', 'MMS GmbH', 'MMS verfügt über ein ausgeprägtes Prozessdenken (''gelebtes Prozesshaus''). Die Digitalisierung soll alle Kern- und Unterstützungsprozesse des Unternehmens erfassen und zudem alle ''Insellösungen'' ersetzen bzw. miteinander verknüpfen. Über 80% aller Digitalprojekte scheitern aufgrund schlechter Planung, unnötigen Druck oder mangelnde Professionalität. Batix konnte hier sein Tandem-Modell einbringen: Ein Organisationsentwickler und ein Softwareentwickler bilden zusammen das externe ''Expertenteam''.', '["Experten-Tandem-Modell","Prozessmanagement","Strategieberatung","Change Management"]'::jsonb, '["Strukturierte Roadmap bis 2025","Fokussierte Umsetzung","Risikominimierung","Nachhaltige Transformation"]'::jsonb, '["Digitalstrategie","Transformation","Beratung"]'::jsonb, NULL, '2019-09-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00')
ON CONFLICT (id) DO NOTHING;
