/*
  # Import Case Studies Part 1

  Import first batch of case studies
*/

INSERT INTO case_studies (id, title, industry, category, challenge, solution, result, duration, company, detailed_description, technologies, outcomes, tags, image_url, date, is_active, created_at, updated_at)
VALUES 
  ('04ed3f0d-7747-480b-9fc2-cf017adba6dc', 'Mixed Reality in der Fabrik', 'Schweißtechnik', 'Smart Factory', 'Entwicklung autonomer Schweißzellen mit digitaler Programmierung', 'Augmented Reality-Steuerung mit HoloLens 2 für WAAM-Verfahren', 'Praxisnahe Demonstration von Industrie 4.0 zum Anfassen', '18 Monate', 'Batix & Kompetenzzentrum Ilmenau', 'Gemeinsam mit dem Mittelstand 4.0-Kompetenzzentrum Ilmenau wurde eine Augmented Reality-Steuerung für eine Schweißanlage entwickelt. Der sogenannte ''Welding Cube'' kommt bei der additiven Fertigung von Bauteilen aus Metall mittels Wire Arc Additive Manufacturing (WAAM) zum Einsatz. Die Software in Kombination mit der HoloLens 2 von Microsoft erzeugt direkt an der Anlage eine digitale Informationsebene innerhalb der realen Welt.', '["Microsoft HoloLens 2","Wire Arc Additive Manufacturing","Augmented Reality","3D-Metallschweißen"]'::jsonb, '["Digitalisierung zum Anfassen","Praxisnahe Demonstration","Zukunftsweisende Schweißtechnologie","Industrie 4.0 Integration"]'::jsonb, '["Augmented Reality","3D-Druck","Innovation"]'::jsonb, NULL, '2020-03-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00'),
  ('16aa7add-6a90-49f4-9478-049f58f0a373', 'Big Data Analyse & Optimierung', 'Diverses', 'Smart Data', 'Nutzung ungenutzter Datenbestände für Prozessoptimierung', 'Software zur sicheren Verarbeitung und Analyse großer Datenmengen', 'Aufdeckung ungenutzter Potenziale und Investitionssicherheit', 'Ongoing', 'Diverse Kunden', 'Unternehmen sammeln (un)bewusst unzählige Daten und Informationen und ''sitzen'' buchstäblich auf einem Schatz. Paradoxerweise nutzen die Wenigsten diesen für die Optimierung von internen Prozessen. Software von Batix hilft Unternehmen große Datenmengen sicher zu verarbeiten und zu analysieren. Das schafft Investitionssicherheit und hebt ungeahnte Potenziale.', '["Big Data Analytics","Datenvisualisierung","Predictive Analytics","Business Intelligence"]'::jsonb, '["Aufdeckung ungenutzter Potenziale","Investitionssicherheit","Prozessoptimierung","Datenbasierte Entscheidungen"]'::jsonb, '["Big Data","Analytics","Optimierung"]'::jsonb, NULL, '2020-01-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00')
ON CONFLICT (id) DO NOTHING;
