/*
  # Import Case Studies Part 5

  Import final batch of case studies
*/

INSERT INTO case_studies (id, title, industry, category, challenge, solution, result, duration, company, detailed_description, technologies, outcomes, tags, image_url, date, is_active, created_at, updated_at)
VALUES 
  ('c1d66926-3c02-4163-8050-fcfae43f8e1a', 'Qualitätssystem Röntgenstrahler QRS', 'Medizintechnik', 'Smart Factory', 'Lückenlose digitale Prozessdokumentation bei reduziertem Personalaufwand', 'Digitaler Zwilling für jede Röntgenröhre mit virtueller Planung', '95% Reduktion der Fehleranalyseaufwände, von 10 Min auf 2 Sek pro Prüfung', '12 Monate', 'Petrick GmbH', 'Die Petrick GmbH Bad Blankenburg nutzt den systemischen Ansatz von BX:SMART FACTORY. Neben der Kostenreduktion durch Prozessoptimierung rückte schnell das firmeninterne Produktcontrolling in den Fokus. Die individuell entwickelte digitale Lösung wurde gemeinsam entwickelt und erfolgreich eingeführt. Das QRS erzeugt für jede Röntgenröhre ein virtuelles Abbild (Digitaler Zwilling).', '["Digitaler Zwilling","Sensordatenerfassung","Simulationsmodelle","Automatisierte Qualitätsprüfung"]'::jsonb, '["95% Reduktion der Fehleranalyseaufwände","Zeitreduktion von 10 Min auf 2 Sek pro Prüfung","Lückenlose Prozessdokumentation","Erhöhte Transparenz und Effizienz"]'::jsonb, '["Digitaler Zwilling","Qualitätssicherung","Automatisierung"]'::jsonb, NULL, '2018-06-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-10-22T22:30:10.218786+00:00'),
  ('ed924444-1b62-4e92-aa17-30c75a36115c', 'Digitalisierung Kunststoffbranche', 'Kunststoffverarbeitung', 'Smart Factory', 'Optimierte Auftragsabwicklung durch smarte Software-Lösungen', 'Eingangsrechnungstool und Werkzeugverwaltung mit hoher Nutzerakzeptanz', 'Zentrale Plattform für alle Rechnungen und präzise Werkzeugverwaltung', '8 Monate', 'KOMOS GmbH', 'Als Auftragsfertiger von Stanz- und Drehteilen, Kunststoff-Spritzteilen und elektromechanischen Baugruppen bündelt KOMOS zahlreiche verschiedene Technologien unter einem Dach. Der Einstieg in die gemeinsame Zusammenarbeit zwischen KOMOS und Batix gelang durch die Einführung des Eingangsrechnungstools. Das Modul bündelt alle eingehenden Rechnungen zentral auf einer Plattform.', '["Eingangsrechnungstool","Werkzeugverwaltungssystem","Zentrale Plattform","Prozessautomatisierung"]'::jsonb, '["Hohe Nutzerakzeptanz","Zentrale Rechnungsbearbeitung","Präzise Werkzeugverwaltung","Nahtlose Integration"]'::jsonb, '["Auftragsabwicklung","Werkzeugverwaltung","Automation"]'::jsonb, NULL, '2021-02-01', true, '2025-08-21T11:05:25.472343+00:00', '2025-08-21T11:05:25.472343+00:00')
ON CONFLICT (id) DO NOTHING;
